export const listDisease = [
  { label: "Covid-19", id: 1994 },
  { label: "The Godfather", id: 1972 },
  { label: "The Godfather: Part II", id: 1974 },
  { label: "The Dark Knight", id: 2008 },
  { label: "12 Angry Men", id: 1957 },
  { label: "Schindler's List", id: 1993 },
  { label: "Pulp Fiction", id: 1994 },
];

export const medicalHistories = [
  {
    id: 1,
    location: "New York City, NY",
    dateTime: "2024-03-19T00:00:00.000Z",
    diseaseName: "Flu",
    faculty: "Internal Medicine",
    doctorName: "Dr. Jane Smith",
    symptoms: "Fever, cough, sore throat",
    prescriptions: "Tamiflu, Acetaminophen",
    totalMoney: 100,
    isDeleted: false,
  },
  {
    id: 2,
    location: "London, UK",
    dateTime: "2024-02-15T10:30:00.000Z",
    diseaseName: "Sprained Ankle",
    faculty: "Orthopedics",
    doctorName: "Dr. Michael Jones",
    symptoms: "Pain, swelling, difficulty walking",
    prescriptions: "Ankle brace, pain medication",
    totalMoney: 250,
    isDeleted: false,
  },
  {
    id: 3,
    location: "Tokyo, Japan",
    dateTime: "2024-01-01T12:00:00.000Z",
    diseaseName: "Food poisoning",
    faculty: "Gastroenterology",
    doctorName: "Dr. Hanako Tanaka",
    symptoms: "Nausea, vomiting, diarrhea",
    prescriptions: "Anti-nausea medication, rehydration solution",
    totalMoney: 50,
    isDeleted: false,
  },
  {
    id: 4,
    location: "Berlin, Germany",
    dateTime: "2023-12-24T16:00:00.000Z",
    diseaseName: "Common cold",
    faculty: "General Practice",
    doctorName: "Dr. Peter Schmidt",
    symptoms: "Runny nose, congestion, cough",
    prescriptions: "Over-the-counter decongestants",
    totalMoney: 20,
    isDeleted: false,
  },
  {
    id: 5,
    location: "Paris, France",
    dateTime: "2023-11-11T11:11:11.000Z",
    diseaseName: "Ear infection",
    faculty: "Pediatrics",
    doctorName: "Dr. Marie Dubois",
    symptoms: "Earache, fever",
    prescriptions: "Amoxicillin",
    totalMoney: 75,
    isDeleted: false,
  },
];
